spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1111111111@qq.com
    password: 111111111 # 授权码
  redis:
    host: 127.0.0.1
#    password: root
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8001
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    com.qf: debug
blog:
  host: http://localhost:${server.port}/


